// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: grpc.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class CovisService
{
  static readonly string __ServiceName = "CovisService";

  static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::UpdateMessage> __Marshaller_UpdateMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::UpdateMessage.Parser.ParseFrom);

  static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Ping = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
      grpc::MethodType.Unary,
      __ServiceName,
      "Ping",
      __Marshaller_google_protobuf_Empty,
      __Marshaller_google_protobuf_Empty);

  static readonly grpc::Method<global::UpdateMessage, global::UpdateMessage> __Method_Sync = new grpc::Method<global::UpdateMessage, global::UpdateMessage>(
      grpc::MethodType.DuplexStreaming,
      __ServiceName,
      "Sync",
      __Marshaller_UpdateMessage,
      __Marshaller_UpdateMessage);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::GrpcReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of CovisService</summary>
  public abstract partial class CovisServiceBase
  {
    public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Ping(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task Sync(grpc::IAsyncStreamReader<global::UpdateMessage> requestStream, grpc::IServerStreamWriter<global::UpdateMessage> responseStream, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for CovisService</summary>
  public partial class CovisServiceClient : grpc::ClientBase<CovisServiceClient>
  {
    /// <summary>Creates a new client for CovisService</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public CovisServiceClient(grpc::Channel channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for CovisService that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public CovisServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected CovisServiceClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected CovisServiceClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::Google.Protobuf.WellKnownTypes.Empty Ping(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return Ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::Google.Protobuf.WellKnownTypes.Empty Ping(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_Ping, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> PingAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return PingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> PingAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_Ping, null, options, request);
    }
    public virtual grpc::AsyncDuplexStreamingCall<global::UpdateMessage, global::UpdateMessage> Sync(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return Sync(new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncDuplexStreamingCall<global::UpdateMessage, global::UpdateMessage> Sync(grpc::CallOptions options)
    {
      return CallInvoker.AsyncDuplexStreamingCall(__Method_Sync, null, options);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override CovisServiceClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new CovisServiceClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(CovisServiceBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_Ping, serviceImpl.Ping)
        .AddMethod(__Method_Sync, serviceImpl.Sync).Build();
  }

  /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, CovisServiceBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_Ping, serviceImpl.Ping);
    serviceBinder.AddMethod(__Method_Sync, serviceImpl.Sync);
  }

}
#endregion
